spring:
  datasource:
    url: 'jdbc:oracle:thin:@localhost:1521:ORCLCDB'
    username: wish
    password: wish
    driver:
      class-name: 'oracle.jdbc.OracleDriver'


  mail:
    host: smtp.gmail.com
    username: crudtestmail@gmail.com
    password: crudtest111
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp


